config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :words do
    post :confirm, on: :collection
  end
  get '/test_word', to: 'words#test_word'
  resources :users
  resources :sessions
  resources :contacts

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  get '/to_slack', to: 'words#to_slack', as: 'button'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :content, length: { in: 1..1000 }

  belongs_to :user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :destroy]
  before_action :redirect_if_not_logged_in
  before_action :set_user

  def index
    @contacts = Contact.all
  end

  def show
    redirect_if_wrong_user_for_contact
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.name.empty?
      @contact.name = current_user.name
    end

    if @contact.email.empty?
      @contact.email = current_user.email
    end

    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to @contact, notice: 'お問い合わせを送信しました'
    else
      render :new
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: '削除しました'
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

  def redirect_if_wrong_user_for_contact
    redirect_to new_session_path if @contact.user != current_user
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="new_contact">
  <%= form_with(model: contact, local: true) do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label :お問い合わせ内容 %>
    <%= form.text_area :content, id: :contact_content, class: :contact_form_input_field %>
      <div class="caution">
        <p>送信完了後、ご指定のメールアドレスに確認メールが届きます<br>もし指定がなければ下記のメールアドレスにメールが届きます</p>
      </div>

      <div class="row">
        <%= form.label :名前 %>
        <%= form.text_field :name, id: :contact_name, placeholder: current_user.name %>
      </div>

      <div class="row">
        <%= form.label :メールアドレス %>
        <%= form.text_field :email, id: :contact_email, placeholder: current_user.email %>
      </div>
    <%= form.submit "送信する", class: :button, title: "送信の確認", data: {confirm: '本当に送りますか？', cancel: "やめる", commit: "送る"} %>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <h1>過去のお問い合わせ</h1>
    <p><%= link_to 'お問い合わせをする', new_contact_path, class: :link_button %></p>

    <% @contacts.each do |contact| %>
     <% if contact.user_id == current_user.id %>
     <div class="contacts_inner">
       <p class="contact_title"><%= link_to contact do %><i class="far fa-envelope-open"></i>&nbsp内容を確認する<% end %></p>
       <p class="contact_content">送信日&nbsp<%= contact.created_at.strftime('%Y/%m/%d') %></p>
     </div>
     <% end %>
    <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h1>お問い合わせフォーム</h1>
  <div class="column-footer">
    <%= link_to user_path(@user), class: :link_button do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
    <%= link_to "過去のお問い合わせ", contacts_path, class: :link_button %>
  </div>

  <%= render 'form', contact: @contact %>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <h1>お問い合わせ内容</h1>
    <div class="contact_details">
      <div class="contact-date">送信日&nbsp<%= @contact.created_at.strftime('%Y/%m/%d') %></div>
      <div class="contact_details_inner">
        <p class="contact_details_inner_title">確認メール受け取りのメールアドレス</p>
        <p class="contact_details_inner_explaination"><%= @contact.email %></p>
      </div>

      <div class="contact_details_inner">
        <p class="contact_details_inner_title">お問い合わせ内容</p>
        <p class="contact_details_inner_explaination"><%= @contact.content %></p>
      </div>
    </div>

  <div class="column-footer">
    <%= link_to "過去のお問い合わせ", contacts_path, class: :link_button %>
  </div>
</div>