config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :words do
    post :confirm, on: :collection
  end
  get '/test_word', to: 'words#test_word'
  resources :users
  resources :sessions
  resources :contacts

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  get '/to_slack', to: 'words#to_slack', as: 'button'
end

app/models/word.rb
class Word < ApplicationRecord
  before_save { term.downcase! }
  validates :term, presence: true, length: { maximum: 50 }, uniqueness: { scope: :user_id }
  validates :memo, presence: true, length: { maximum: 300 }
  belongs_to :user
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_user
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = set_user.words.all
    @q = Word.ransack(params[:q])
    @q.sorts = 'id asc' if @q.sorts.empty?
    @search_results = @q.result(distinct: true)
    start_date_cannot_be_later_than_finish_date
    registered_words_of_the_day
  end

  def test_word
    @a = Word.find_by(id: params[:id])
    @words = set_user.words.all
    if @words.present?
      @random_word = @words.sample
    end
  end

  def to_slack
    registered_words_of_the_day
    terms_of_my_registered_words = []
    @registered_words_of_the_day.each do |words|
      if words.user_id == current_user.id
        terms_of_my_registered_words << words.term
      end
    end
    notify_to_slack(terms_of_my_registered_words)
  end

  def new
    if params[:back]
      @word = Word.new(word_params)
    else
      @word = Word.new
    end
  end

  def create
    @word = Word.new(word_params)
    @word.user_id = current_user.id
    if @word.save
      redirect_to words_path, notice: '単語を登録しました'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @word.update(word_params)
      redirect_to word_path(@word.id), notice: '単語を編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @word.destroy
    redirect_to words_path, notice: '単語を削除しました'
  end

  def confirm
    @word = Word.new(word_params)
    @word.user_id = current_user.id
    render :new if @word.invalid?
  end

  private

  def word_params
    params.require(:word).permit(:term, :memo, :user_id)
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def registered_words_of_the_day
    today = Date.today
    @registered_words_of_the_day = Word.where(created_at: today.in_time_zone.all_day)
  end

  def notify_to_slack(terms_of_my_registered_words)
    text = <<-EOS
-----------------------------
#{@current_user.name}さんの今日の単語

▼単語
#{terms_of_my_registered_words.join("\n")}
    EOS
    Slack.chat_postMessage text: text, username: "単語登録のお知らせ", channel: "#test_kaoru2"
  end

  def start_date_cannot_be_later_than_finish_date
    start_date = [@q.created_at_gteq(1i), @q.created_at_gteq(2i), @q.created_at_gteq(3i)]
    finish_date = [@q.created_at_lteq_end_of_day(1i), @q.created_at_lteq_end_of_day(2i), @q.created_at_lteq_end_of_day(3i)]
    flash[:notice] = "終了日は開始日より前に設定してください。" if start_date.join > finish_date.join
  end

end

app/helpers/words_helper.rb
module WordsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_words_path
    elsif action_name ="edit"
      word_path
    end
  end
end

app/views/words/_form.html.erb
<%= form_with(model: @word, local: true, url: choose_new_or_edit, html: {id: 'word_form', class: 'form'}) do |f| %>
  <% if @word.errors.any? %>
    <div id = "error_explanation">
      <ul>
        <% @word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="word_term">
    <%= f.label "単語" %>
    <%= f.text_field :term, id: :word_term_registration, maxlength: 50 %>
  </div>

  <div class="word_memo">
    <%= f.label "意味、説明" %>
    <%= f.text_area :memo, id: :word_memo_registration, maxlength: 300 %>
  </div>

  <%= f.submit "登録", class: :button, id: :word_registration_button %>
<% end %>

<div class="column-footer">
  <%= link_to words_path(current_user.id), class: :link_button do %>
    <i class="fas fa-arrow-left"></i>
  <% end %>
</div>


<script>
// 残り文字数カウント機能
  //プログラムで使用する変数の設定
  $(function() {
    var button = document.getElementById('word_registration_button');
    var form = document.getElementById('word_form');
    var termArea = document.getElementById('word_term_registration');
    var memoArea = document.getElementById('word_memo_registration');

    var maxTermNum = termArea.getAttribute('maxlength');
    var maxMemoNum = memoArea.getAttribute('maxlength');

  // 残り文字を表示する要素の追加
    var termMsg = document.createElement('div');
    var termParent = termArea.parentElement;

    var memoMsg = document.createElement('div');
    var memoParent = memoArea.parentElement;

  // イベントの指定（テキストエリアでキーをタイプした時残り文字数を変化させる）
    termArea.addEventListener('keyup', function() {
      var currentTermNum = termArea.value.length;
      termParent.insertBefore(termMsg, null);
      termMsg.innerHTML = '残り入力可能字数：' + (maxTermNum - currentTermNum);

      if (currentTermNum <= 49) {
        termMsg.style.color = "#000";
      } else {
        termMsg.style.color = "red";
      }
    });

    memoArea.addEventListener('keyup', function() {
      var currentMemoNum = memoArea.value.length
      memoParent.insertBefore(memoMsg, null);
      memoMsg.innerHTML = '<p>残り入力可能文字数：' + (maxMemoNum - currentMemoNum) + '</p>';

      if (currentMemoNum <= 299) {
        memoMsg.style.color = "#000";
      } else {
        memoMsg.style.color = "red";
      }
    });
  });
</script>

app/views/words/_render_test_word.html.erb
<h1><%= @random_word.term %></h1>
<p><%= link_to "詳細を確認", word_path(@random_word) %></p>

app/views/words/_test_word.html.erb
<h1><%= @random_word.term %></h1>
<p><%= link_to "詳細を確認", word_path(@random_word) %></p>

app/views/words/confirm.html.erb
<div class="container">
  <h1>登録の確認</h1>

  <%= form_with(model: @word, url: words_path, local: true) do |f| %>
    <%= f.hidden_field :term %>
    <%= f.hidden_field :memo %>
    <div class="confirm_inner">
      <div class="confirm_details">
        <div class="confirm_details_inner">
          <p class="confirm_details_inner_title">単語</p>
          <p class="confirm_details_inner_explaination"><%= @word.term %></p>
        </div>

        <div class="confirm_details_inner">
          <p class="confirm_details_inner_title">意味、説明</p>
          <p class="confirm_details_inner_explaination word_memo_confirmation"><%= @word.memo %></p>
        </div>

        <p class="register_button"><%= f.submit "登録", class: :button %></p>
      </div>
    </div>
  <% end %>

  <div class="column-footer">
  <%= form_with(model: @word, url: new_word_path, local: true, method: 'get') do |f| %>
    <%= f.hidden_field :term %>
    <%= f.hidden_field :memo %>
    <%= f.submit "戻る", name: 'back', class: :button %>
  <% end %>
  </div>
</div>

app/views/words/edit.html.erb
<div class="container">
  <h1>単語の修正</h1>
  <%= render 'form' %>
</div>

app/views/words/index.html.erb
<div class="container">
  <h1>単語検索</h1>
  <div class="words_search">
    <%= search_form_for @q do |f| %>
      <div class="row">
        <%= f.label :term_cont, "部分一致検索", placeholder: "単語を入力してください", class: "col-sm-12 col-md-3" %>
        <%= f.search_field :term_cont, class: "search_field" %>
      </div>
      <div class="row">
        <%= f.label :created_at, '登録日付検索', class: "col-md-12 col-lg-3" %>
        <div class="col-lg-8">
          <div class="row">
            <div class="col-sm-12 col-md-6">
              開始日<%= f.date_select :created_at_gteq,
                                include_blank: true,
                                use_month_numbers: true,
                                start_year: 2018,
                                end_year: Date.today.year,
                                date_separator: '/'
              %>
            </div>
            <div class="col-sm-12 col-md-6">
              終了日<%= f.date_select :created_at_lteq_end_of_day,
                                include_blank: true,
                                use_month_numbers: true,
                                start_year: 2018,
                                end_year: Date.today.year,
                                date_separator: '/'
               %>
             </div>
            </div>
         </div>
       </div>

      <%= f.submit "検索", class: :button %>
      <%= link_to 'クリア', request.path, class: :clear_button %>

    <% end %>
  </div>


  <h1>登録した単語一覧</h1>
  <div class="words_list">
    <div class="words_list_inner">
      <div class="words_list_inner_header">
        <p class="row">
          <%= sort_link(@q, :term, 'abc順並び替え', default_order: :asc) %>
          <%= sort_link(@q, :created_at, '登録日時順並び替え', default_order: :asc) %>
        </p>
      </div>

      <div class="words_list_inner_body">
        <div class="row">
        <% @search_results.each do |search_result| %>
          <% if search_result.user_id == current_user.id %>
            <p class="col-sm-12 col-md-6 col-lg-4"><%= link_to word_path(search_result.id) do %><%= search_result.term %><% end %></p>
          <% end %>
        <% end %>

        <% unless @search_results.find_by(user_id: current_user.id).present? %>
          <p><i class="fas fa-exclamation-triangle"></i>現在登録している単語はありません。新しい単語の登録から早速始めましょう。</p>
        <% end %>

        </div>
      </div>
    </div>

    <p><%= link_to '新しい単語の登録', new_word_path, class: :link_button %></p>
    <p class="words_list_footer">登録単語数&nbsp全<%= @words.size %>個</p>
  </div>

  <div class="words_to_slack">
    <h1>Slackで共有する</h1>
    <div class="send_registered_words_of_the_day">
      <p class="to_slack">今日登録した単語をslackに送りましょう。(注：卒業課題用のslackチャンネルは&nbsp<%= link_to  '#test_kaoru2' ,'https://diveintocode.slack.com/messages/CCA5K407M/details/', target: "_new" %>です）</p>
        <% @registered_words_of_the_day.each do |my_registered_word| %>
          <% if my_registered_word.user_id == current_user.id %>
            <% if my_registered_word.present? %>
              <%= link_to my_registered_word.term, word_path(my_registered_word.id), class: :link_button %>&nbsp
            <% end %>
          <% end %>
        <% end %>

        <% unless @registered_words_of_the_day.find_by(user_id: current_user.id).present? %>
          <i class="fas fa-exclamation-triangle"></i>今日登録した単語はありません。
        <% end %>
        <%= button_to 'Slackに送る', button_path, class: :button, method: :get, title: "Slackへの送信の確認", data: {confirm: '本当に送りますか？', cancel: "やめる", commit: "送る"} %>
    </div>
  </div>

  <div>
    <h1>応用編</h1>
    <p>単語スライダーを使って今までの単語を総復習しましょう。</p>
    <p>下の「切り替え時間を設定」から何秒後ごとに単語を切り替えたいか指定して早速始めましょう。</p>
    <button id="setTimeBtn" class="button">切り替え時間を設定</button>

    <div class="words_test">
      <h5>単語スライダー</h5>
      <div class="words_test_inner">
        <% if @words.present? %>
          <div class="random_tester">
            <div id="test_slider">
              <p>ARE YOU READY?</p>
            </div>
            <%= link_to "スタート", test_word_path, remote: true, class: :link_button, id: :nextWordBtn %>
          </div>
        <% else %>
          <p><i class="fas fa-exclamation-triangle"></i>現在登録している単語はありません。</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
// 単語スライダーのタイマー機能
  $(function() {
    // ユーザーがタイマーの長さを指定する
    var setTimeBtn = document.getElementById('setTimeBtn');
    setTime = 5;
    setTimeBtn.addEventListener('click', function() {
      setTime = prompt('半角英数で時間を指定してください（秒）。初期値は5秒に設定してあります','5');
      // 入力制限
      if((setTime == "") || (setTime == null)) {
        setTime = 5;
      } else if(setTime.match(/^[0-9]+$/)){
        if(setTime == 0) {
          alert("半角数字のみを入力してください。小数や分数、全角入力は受け付けません。");
          setTime = 5;
        }
        // promptでとると数字でも文字列として受け取ってるから数列型にする
        setTime = parseFloat(setTime);
      } else {
        alert("半角数字のみを入力してください。小数や分数、全角入力は受け付けません。");
        setTime = 5;
      }
    });

    var nextWordBtn = document.getElementById('nextWordBtn');
    // スライダーが始まったら'スタートボタン'を'次の単語へ'に変えて、指定時間ごとにタイマーをリセットして終了の文字に色をつける
    var timer;
    nextWordBtn.addEventListener('click', function() {
      clearTimeout(timer);

      timer = setTimeout(sliderTimer, (setTime+1)*1000+1000);
      function sliderTimer(timer) {
        var showTime = document.getElementById('showTime');
        showTime.style.color = "red";
      };
      // ボタンの書き換え
      nextWordBtn.innerHTML = '次の単語へ';
    });

    // 残り時間を表示する
    var count;
    nextWordBtn.addEventListener('click', function() {
      var timeRemain = setTime+1;
      var timeRemainMsg = document.createElement('div');
      timeRemainMsg.setAttribute('id', 'showTime');
      var parent = nextWordBtn.parentElement;
      parent.insertBefore(timeRemainMsg, null);

      // 1秒ずつ残り時間を減らしていく
      count = setInterval(startCounting, 1000);
      function startCounting(count) {
        timeRemain--;
        timeRemainMsg.innerHTML = '制限時間:' + timeRemain + '秒';
        if (timeRemain == 0) {
          timeRemainMsg.innerHTML = '制限時間:0秒';
          clearInterval(count);
        } else if (timeRemain < 0) {
          timeRemainMsg.innerHTML = '制限時間終了';
          clearInterval(count);
        }

        // 途中で次の単語ボタンや切り替え時間設定ボタンを押した時、カウントを中止して残り時間を非表示にする。
        nextWordBtn.addEventListener('click', function(count) {
          timeRemainMsg.remove();
          clearInterval(count);
        });

        setTimeBtn.addEventListener('click', function(count) {
          timeRemainMsg.remove();
          clearInterval(count);
          nextWordBtn.innerHTML = 'もう一度始める';
        });
      };
    });
  });

</script>

app/views/words/new.html.erb
<div class="container">
  <h1>単語の登録</h1>
  <%= render 'form' %>
</div>

app/views/words/show.html.erb
<div class="container">
  <h1>単語詳細</h1>

  <div class="word_details">
    <div class="word_details_inner">
      <p class="word_details_inner_title">単語</p>
      <p class="word_details_inner_explaination"><%= @word.term %></p>
    </div>

    <div class="word_details_inner">
      <p class="word_details_inner_title">意味、説明</p>
      <p class="word_details_inner_explaination"><%= @word.memo %></p>
    </div>

    <div class="word_details_inner registered_day">
      <p class="word_details_inner_title">登録日</p>
      <p class="word_details_inner_explaination"><%= @word.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    </div>

    <%= link_to '編集', edit_word_path(@word.id), class: :link_button %>
    <%= link_to '削除', word_path(@word.id), class: :link_button, method: :delete, title: "削除の確認", data: {confirm: '本当に削除しますか？', cancel: "やめる", commit: "削除する"} %>
  </div>

  <div class="column-footer">
    <%= link_to words_path(current_user.id), class: :link_button do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  </div>
</div>

app/views/words/test_word.js.erb
$('#test_slider').html("<%= escape_javascript(render 'test_word') %>");

app/views/words/to_slack.html.erb
<div class="container">
  <div class="contacts_inner">
    <p class="contact_title"><h2>slackに通知しました</h2></p>
    <p class="contact_content"><%= link_to '戻る', words_path, class: :link_button %></p>
  </div>
</div>