config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  resources :words do
    post :confirm, on: :collection
  end
  get '/test_word', to: 'words#test_word'
  resources :users
  resources :sessions
  resources :contacts

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  get '/to_slack', to: 'words#to_slack', as: 'button'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Federo|Noto+Serif+JP" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <header>
      <div class="top_menu">
        <% if logged_in? %>
          <ul class="lg_screen">
            <li><%= link_to_unless_current 'HOME', user_path(@user), class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "単語帳", words_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "ユーザー一覧", users_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "チャットルーム", conversations_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "プロフィール編集", edit_user_path(@user.id), class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "お問い合わせ", new_contact_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete, title: "ログアウトの確認", data: {confirm: 'お疲れ様でした。本当にログアウトしますか？', cancel: "やめる", commit: "ログアウトする"}, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
          </ul>

          <ul class="sm_screen">
            <li><%= link_to_unless_current 'HOME', user_path(@user), class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "単語帳", words_path, class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "ユーザー", users_path, class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "チャット", conversations_path, class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "プロフィール", edit_user_path(@user.id), class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "お問い合わせ", new_contact_path, class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete, title: "ログアウトの確認", data: {confirm: 'お疲れ様でした。本当にログアウトしますか？', cancel: "やめる", commit: "ログアウトする"}, class: :for_sm_screen, style: "color:#fff;" %></li>
          </ul>
        <% else %>
          <ul class="lg_screen">
            <li><%= link_to_unless_current "TOPページに戻る", root_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
          </ul>
          <ul class="sm_screen">
            <li><%= link_to_unless_current "TOPページに戻る", root_path, class: :for_sm_screen, style: "color:#fff;" %></li>
          </ul>
        <% end %>
      </div>

      <div class="general_top">
        <div class="top_overlay_one">
        </div>

        <div class="top_overlay_two">
        </div>

        <div class="top_logo">
          <% if logged_in? %>
            <%= link_to image_tag('logo_white.png', { border: '0', alt: 'マイページ', width: "30%"}), user_path(current_user.id) %>
          <% else %>
            <%= image_tag('logo_white.png', { border: '0', width: "30%"}) %>
          <% end %>
          <p>YET.</p>
        </div>
      </div>

      <div class="header-overlay">
      </div>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key} alert alert-info", role: "alert") %>
      <% end %>
    </header>

    <%= yield %>

    <footer>
      <div class="footer_image_application">
      </div>

      <div class="footer_overlay">
      </div>

      <div class="footer_inner">
        <p>Graduation assignment by Kaoru Onuki 201804<br>@DIVE INTO CODE Corp.</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/second_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Federo|Noto+Serif+JP" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <header>
      <div class="top">
        <div class="top_overlay_one">
        </div>

        <div class="top_overlay_two">
        </div>

        <div class="top_logo">
          <%= image_tag('logo_white.png', { border: '0', width: "70%"}) %>
          <h5>YET.</h5>
        </div>
      </div>

      <div class="top_menu">
        <% if logged_in? %>
          <ul class="lg_screen">
            <li><%= link_to_unless_current 'マイページ', user_path(current_user), class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
          </ul>
          <ul class="sm_screen">
            <li><%= link_to_unless_current 'マイページ', user_path(current_user), class: :for_sm_screen, style: "color:#fff;" %></li>
          </ul>
        <% else %>
          <ul class="lg_screen">
            <li><%= link_to_unless_current "アカウント登録", root_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
            <li><%= link_to_unless_current "ログイン", new_session_path, class: :for_lg_screen, style: "color:#444;" %><i class="fas fa-angle-left"></i></li>
          </ul>
          <ul class="sm_screen">
            <li><%= link_to_unless_current "アカウント登録", root_path, class: :for_sm_screen, style: "color:#fff;" %></li>
            <li><%= link_to_unless_current "ログイン", new_session_path, class: :for_sm_screen, style: "color:#fff;" %></li>
          </ul>
        <% end %>
      </div>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key} alert alert-info", role: "alert") %>
      <% end %>
    </header>

    <%= yield %>

    <footer>
      <div class="footer_image_second_application">
      </div>

      <div class="footer_overlay">
      </div>

      <div class="footer_inner">
        <p>Graduation assignment by Kaoru Onuki 201804<br>@DIVE INTO CODE Corp.</p>
      </div>
    </footer>
  </body>
</html>